store/orders/urls.py
from django.urls import path

from orders.views import OrderCreateView

app_name = "orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="order_create"),
]

store/products/urls.py
from django.urls import path

from products.views import ProductsListView, basket_add, basket_remove

app_name = "products"

urlpatterns = [
    path("", ProductsListView.as_view(), name="index"),
    path("category/<int:category_id>/", ProductsListView.as_view(), name="category"),
    path("baskets/add/<int:product_id>/", basket_add, name="basket_add"),
    path("baskets/remove/<int:basket_id>/", basket_remove, name="basket_remove"),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

from products.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = "users"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "verify/<str:email>/<uuid:code>",
        EmailVerificationView.as_view(),
        name="email_verification",
    ),
]

store/products/models.py
from django.db import models

from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):  # type: ignore
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField()
    image = models.ImageField(upload_to="products_images")
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):  # type: ignore
        return f"{self.category}: {self.name}"


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()  # type: ignore

    def __str__(self):
        return f"Корзина для {self.user.username} | Продукт: {self.product.name}"  # type: ignore

    def sum(self):
        return self.product.price * self.quantity  # type: ignore

store/products/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import HttpResponseRedirect, redirect
from django.views.generic import ListView, TemplateView


from common.views import TitleMixin

from .models import Basket, Product, ProductCategory


class IndexView(TitleMixin, TemplateView):
    template_name = "products/index.html"
    title = "Store"


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = "products/products.html"
    paginate_by = 3
    title = "Store -> Каталог"

    def get_queryset(self):
        category_id = self.kwargs.get("category_id")
        if category_id:
            category = ProductCategory.objects.get(id=category_id)  # pyright: ignore
            products = Product.objects.filter(category=category)  # pyright: ignore
        else:
            products = super(ProductsListView, self).get_queryset()

        return products

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context["categories"] = ProductCategory.objects.all()  # type: ignore
        context["category_id"] = self.kwargs.get("category_id")

        return context


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)  # type: ignore

    try:
        basket = Basket.objects.get(user=request.user, product=product)  # type: ignore
        basket.quantity += 1
        basket.save()
    except ObjectDoesNotExist:
        Basket.objects.create(product=product, user=request.user, quantity=1)  # type: ignore

    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def basket_remove(request, basket_id):
    basket_item = Basket.objects.filter(id=basket_id, user=request.user).first()
    if basket_item is not None:
        basket_item.delete()
    return redirect(to=request.META["HTTP_REFERER"])

store/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta content="width=device-width, initial-scale=1, shrink-to-fit=no"
              name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <title>{{ title }}</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
              rel="stylesheet" />
        <!-- Custom styles for this template -->
        {% block css %}
        {% endblock css %}
    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">Store</a>
                <button aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                        class="navbar-toggler"
                        data-target="#navbarResponsive"
                        data-toggle="collapse"
                        type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a aria-expanded="false"
                               class="nav-link dropdown-toggle"
                               data-bs-toggle="dropdown"
                               href="#"
                               id="navbarDropdown"
                               role="button">
                                <i class="fas fa-user-circle"></i>
                            </a>
                            <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="orders/orders.html">Заказы</a>
                                </li>
                                {% if user.is_superuser or user.is_staff %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider" />
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    {% block content %}
    {% endblock content %}
    {% block footer %}
    {% endblock footer %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script crossorigin="anonymous"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- FontAwesome script -->
    <script crossorigin="anonymous"
            src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}"></script>
</body>
</html>

store/products/templates/products/baskets.html
{% load humanize %}
{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина
        <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.product.name }}</h5>
                <p class="card-text">{{ basket.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input class="form-control"
                                   min="0"
                                   name="basketID"
                                   type="number"
                                   value="{{ basket.quantity }}" />
                        </div>
                        <div class="col-lg-4">{{ basket.sum|intcomma }} руб.</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right"
       href="{% url 'orders:order_create' %}">Оформить заказ</a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">Корзина пуста</h4>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet" />
{% endblock css %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Store</h1>
                    <p>
                        Новые образы и лучшие бренды на Store. Бесплатная доставка по
                        всему миру! Аутлет: до -70% Собственный бренд. -20% новым
                        покупателям.
                    </p>
                    <button class="btn btn-lg" id="start-purchase-btn" type="button">
                        <a href="{% url 'products:index' %}" id="start-purchase-link">Начать покупки</a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

store/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load humanize %}
{% load static cache %}
{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet" />
{% endblock css %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a class="list-group-item"
                           href="{% url 'products:category' category.id %}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <!-- /.col-lg-3 -->
            <div class="col-lg-9">
                <div class="carousel slide my-4"
                     data-ride="carousel"
                     id="carouselExampleIndicators">
                    <ol class="carousel-indicators">
                        <li class="active"
                            data-slide-to="0"
                            data-target="#carouselExampleIndicators"></li>
                        <li data-slide-to="1" data-target="#carouselExampleIndicators"></li>
                        <li data-slide-to="2" data-target="#carouselExampleIndicators"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img alt="First slide"
                                 class="d-block img-fluid"
                                 src="{% static 'vendor/img/slides/slide-1.jpg' %}" />
                        </div>
                        <div class="carousel-item">
                            <img alt="Second slide"
                                 class="d-block img-fluid"
                                 src="{% static 'vendor/img/slides/slide-2.jpg' %}" />
                        </div>
                        <div class="carousel-item">
                            <img alt="Third slide"
                                 class="d-block img-fluid"
                                 src="{% static 'vendor/img/slides/slide-3.jpg' %}" />
                        </div>
                    </div>
                    <a class="carousel-control-prev"
                       data-slide="prev"
                       href="#carouselExampleIndicators"
                       role="button">
                        <span aria-hidden="true" class="carousel-control-prev-icon"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next"
                       data-slide="next"
                       href="#carouselExampleIndicators"
                       role="button">
                        <span aria-hidden="true" class="carousel-control-next-icon"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="row">
                    {% cache 30 object_list page_obj.number category_id %}
                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img alt="" class="card-img-top" src="{{ product.image.url }}" />
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price|intcomma }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a class="btn btn-outline-success"
                                       href="{% url 'products:basket_add' product.id %}">Отправить в корзину</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endcache %}
            </div>
            {% if page_obj.has_other_pages %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" disabled href="#" tabindex="-1">
                                        {% endif %}
                                    Предыдущий</a>
                                </li>
                                {% for count in page_obj.paginator.page_range %}
                                    {% if page_obj.number == count %}
                                        <li class="page-item active">
                                        {% elif count >= page_obj.number|add:-2 and count <= page_obj.number|add:2 %}
                                            <li class="page-item">
                                            {% endif %}
                                            <a class="page-link" href="?page={{ count }}">{{ count }}</a>
                                        </li>
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                            {% else %}
                                                <li class="page-item disabled">
                                                    <a class="page-link" disabled href="#" tabindex="-1">
                                                    {% endif %}
                                                Следующий</a>
                                            </li>
                                        </ul>
                                    </nav>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endblock content %}
                {% block footer %}
                    <footer class="py-5 bg-dark">
                        <div class="container">
                            <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
                        </div>
                    {% endblock footer %}